### ISSUE TITLE
S3 bucket model not found error

### ISSUE THREAD

**Issue by venkatapavithra** [HHousen/DocSum#2]
Traceback (most recent call last):
  File "run_summarization.py", line 325, in <module>
    main()
  File "run_summarization.py", line 310, in main
    evaluate(args)
  File "run_summarization.py", line 34, in evaluate
    model = BertAbs.from_pretrained("bertabs-finetuned-cnndm")
  File "D:\anaconda3\lib\site-packages\transformers\modeling_utils.py", line 546, in from_pretrained
    **kwargs,
  File "D:\anaconda3\lib\site-packages\transformers\configuration_utils.py", line 202, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\anaconda3\lib\site-packages\transformers\configuration_utils.py", line 272, in get_config_dict
    raise EnvironmentError(msg)
OSError: Couldn't reach server at 'https://s3.amazonaws.com/models.huggingface.co/bert/remi/bertabs-finetuned-cnndm-extractive-abstractive-summarization-config.json' to download pretrained model configuration file.

I'm trying to run the code but facing the above error. The code fails to download the config file saying the file not found.
Could you please help me to resolve this issue?
i tried to access the model directly using the provided link but it raises the error "no such key"

**Comment by HHousen** [comment]
Hello @venkatapavithra. This happened because the [huggingface/transformers](https://github.com/huggingface/transformers) repository changed their CDN, and thus their model URLs are different. I've updated the URL in commit [6579d79](https://github.com/HHousen/DocSum/commit/6579d79b3787ac1af37505e5e3dc31b2f074ca40), but I may need to look into a different solution so ensure that this does not happen again. Try pulling the repository again. Does the code work now?
